DROP TABLE IF EXISTS elephants;
DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS zebra;
DROP TABLE IF EXISTS tiger;

CREATE TABLE elephants (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);

CREATE TABLE cats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);

CREATE TABLE dogs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);

CREATE TABLE zebra (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);

CREATE TABLE tiger (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);