DROP TABLE IF EXISTS gocarts;
DROP TABLE IF EXISTS snowmobiles;
DROP TABLE IF EXISTS fourwheelers;
DROP TABLE IF EXISTS motorcycles;
DROP TABLE IF EXISTS cars;


CREATE TABLE gocarts (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT
);
CREATE TABLE snowmobiles (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT
);
CREATE TABLE fourwheelers (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT
);
CREATE TABLE motorcycles (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT
);
CREATE TABLE cars (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT
);